#pragma once
// Auto-generated offsets from IL2CPP dump
// Generated by offset_finder.py
// DO NOT EDIT MANUALLY - Run `python tools/offset_finder.py` to regenerate

#include <cstdint>

namespace Offsets {

	// UnityEngine Methods (extracted directly)
	namespace Unity {
		constexpr uintptr_t Camera_WorldToScreenPoint = 0x7AAC40;
		constexpr uintptr_t Transform_get_position = 0x9FAE30;
		constexpr uintptr_t Transform_set_position = 0x9FB5A0;
		constexpr uintptr_t Transform_get_rotation = 0x9FAFA0;
		constexpr uintptr_t Transform_set_rotation = 0x9FB640;
		constexpr uintptr_t Camera_get_main = 0x7AB060;
	}

	// Hyperstrange.WARPZ.Player
	namespace Player {
		// Fields
		constexpr uintptr_t OnStart = 0x0; // Action<Player>
		constexpr uintptr_t OnFinish = 0x8; // Action<Player>
		constexpr uintptr_t OnDeath = 0x10; // Action<Player>
		constexpr uintptr_t OnFinishWarpSuccess = 0x40; // Action<PlayerWarpComponent>
		constexpr uintptr_t OnButtonSuccess = 0x48; // Action<PlayerWarpComponent>
		constexpr uintptr_t OnWarpSuccess = 0x50; // Action<PlayerWarpComponent>
		constexpr uintptr_t OnWarpFail = 0x58; // Action<PlayerWarpComponent>
		constexpr uintptr_t OnWarpFinderUpdate = 0x60; // Action<PlayerWarpComponent>
		constexpr uintptr_t OnComboIncremented = 0x68; // Action<PlayerComboComponent>
		constexpr uintptr_t OnComboTimeOutUpdate = 0x70; // Action<PlayerComboComponent>
		constexpr uintptr_t OnComboTimedOut = 0x78; // Action<PlayerComboComponent>
		constexpr uintptr_t OnOxygenEnd = 0x80; // Action<PlayerOxygenComponent>
		constexpr uintptr_t OnOxygenUpdate = 0x88; // Action<PlayerOxygenComponent>
		constexpr uintptr_t OnLowOxygenPulse = 0x90; // Action<PlayerOxygenView>
		constexpr uintptr_t OnBreak = 0x98; // Action<PlayerBreakComponent>
		constexpr uintptr_t OnRespawn = 0xA0; // Action<Player>
		constexpr uintptr_t OnDebugNoClipChanged = 0xA8; // Action
		constexpr uintptr_t OnDebugViewChanged = 0xB0; // Action
		constexpr uintptr_t OnDebugComboIncremented = 0xB8; // Action
		constexpr uintptr_t OnDebugTimeScaleChanged = 0xC0; // Action
		constexpr uintptr_t OnDebugOxygenChanged = 0xC8; // Action
		constexpr uintptr_t _cameraTransform = 0xD0; // Transform
		constexpr uintptr_t _playerSpawnPoint = 0xD8; // PlayerSpawnPoint
		constexpr uintptr_t _movementComponent = 0xE0; // PlayerMovementComponent
		constexpr uintptr_t _timeComponent = 0xE8; // PlayerTimeComponent
		constexpr uintptr_t _statsComponent = 0xF0; // PlayerStatsComponent
		constexpr uintptr_t _debugComponent = 0xF8; // PlayerDebugComponent
		constexpr uintptr_t <Camera>k__BackingField = 0x100; // Camera
		constexpr uintptr_t <IsActive>k__BackingField = 0x108; // bool
		constexpr uintptr_t <WarpComponent>k__BackingField = 0x110; // PlayerWarpComponent
		constexpr uintptr_t <ComboComponent>k__BackingField = 0x118; // PlayerComboComponent

		// Methods
		constexpr uintptr_t Awake = 0x138C7C0; // void
		constexpr uintptr_t OnEnable = 0x138CCD0; // void
		constexpr uintptr_t OnDisable = 0x138CA00; // void
		constexpr uintptr_t OnLevelPrepareStart = 0x138CFB0; // void
		constexpr uintptr_t OnLevelStart = 0x138D0C0; // void
		constexpr uintptr_t OnLevelPrepareEnd = 0x138CFA0; // void
		constexpr uintptr_t OnFinishWarp = 0x138CFA0; // void
		constexpr uintptr_t get_Camera = 0x2DA4F0; // Camera
		constexpr uintptr_t set_Camera = 0x2DA9C0; // void
		constexpr uintptr_t get_CameraTransform = 0x585F20; // Transform
		constexpr uintptr_t get_IsActive = 0x2DA510; // bool
		constexpr uintptr_t set_IsActive = 0x2DA9E0; // void
		constexpr uintptr_t get_IsMoving = 0x138E180; // bool
		constexpr uintptr_t get_MinimalSpeed = 0x138E1B0; // bool
		constexpr uintptr_t get_CurrentSpeed = 0x138E0C0; // ObscuredFloat
		constexpr uintptr_t get_SpeedStat = 0x138E210; // SpeedStat
		constexpr uintptr_t get_CurrentTime = 0x138E100; // TimeStat
		constexpr uintptr_t get_WarpComponent = 0x2F9510; // PlayerWarpComponent
		constexpr uintptr_t set_WarpComponent = 0x2DAB10; // void
		constexpr uintptr_t get_ComboComponent = 0x4F8F50; // PlayerComboComponent
		constexpr uintptr_t set_ComboComponent = 0x4FB120; // void
		constexpr uintptr_t GetLastRunInfo = 0x138C9B0; // LevelRunInfo
		constexpr uintptr_t GetAchievementsStats = 0x138C970; // LevelAchievementsStats
		constexpr uintptr_t get_DebugNoClip = 0x138E140; // bool
		constexpr uintptr_t get_DebugHiddenView = 0x138E120; // bool
		constexpr uintptr_t get_DebugOxygenDisabled = 0x138E160; // bool
		constexpr uintptr_t .ctor = 0x138D270; // void
		constexpr uintptr_t .cctor = 0x138D0D0; // void
	}

	// Hyperstrange.WARPZ.TimeManager
	namespace TimeManager {
		// Fields
		constexpr uintptr_t OnTimeScaleChanged = 0x0; // Action<float>
		constexpr uintptr_t <CurrentTimeScale>k__BackingField = 0x8; // float

		// Methods
		constexpr uintptr_t SetTimeScale = 0x1345B80; // void
		constexpr uintptr_t get_CurrentTimeScale = 0x1345DC0; // float
		constexpr uintptr_t set_CurrentTimeScale = 0x1345E20; // void
		constexpr uintptr_t .ctor = 0x1345D50; // void
		constexpr uintptr_t .cctor = 0x1345C70; // void
	}

	// Hyperstrange.WARPZ.FinishPanel
	namespace FinishPanel {

		// Methods
		constexpr uintptr_t .ctor = 0x1357010; // void
	}

	// Hyperstrange.WARPZ.PlayerMovementComponent
	namespace PlayerMovementComponent {
		// Fields
		constexpr uintptr_t _minSpeed = 0x48; // float
		constexpr uintptr_t _deltaSpeed = 0x4C; // float
		constexpr uintptr_t _acceleration = 0x50; // float
		constexpr uintptr_t _breakDeltaSpeed = 0x54; // float
		constexpr uintptr_t _breakDeceleration = 0x58; // float
		constexpr uintptr_t _idleDeceleation = 0x5C; // float
		constexpr uintptr_t _idleDecelerationDelay = 0x60; // float
		constexpr uintptr_t _speedBeforeSlowMotion = 0x64; // float
		constexpr uintptr_t _currentAcceleration = 0x68; // float
		constexpr uintptr_t _idleDecelerate = 0x6C; // bool
		constexpr uintptr_t _idleTween = 0x70; // Tween
		constexpr uintptr_t _direction = 0x78; // Vector3
		constexpr uintptr_t _speedStat = 0x84; // SpeedStat
		constexpr uintptr_t <IsMoving>k__BackingField = 0x88; // bool
		constexpr uintptr_t <CurrentSpeed>k__BackingField = 0x8C; // ObscuredFloat
		constexpr uintptr_t <TargetSpeed>k__BackingField = 0xA4; // ObscuredFloat
		constexpr uintptr_t <MaxSpeed>k__BackingField = 0xBC; // ObscuredFloat

		// Methods
		constexpr uintptr_t OnEnable = 0x1388710; // void
		constexpr uintptr_t OnDisable = 0x1388330; // void
		constexpr uintptr_t OnFinish = 0x1388AF0; // void
		constexpr uintptr_t OnRespawn = 0x1388E00; // void
		constexpr uintptr_t OnWarpSuccess = 0x1389010; // void
		constexpr uintptr_t HandleIdle = 0x1387E30; // void
		constexpr uintptr_t OnWarpFail = 0x1389000; // void
		constexpr uintptr_t OnBreak = 0x1388320; // void
		constexpr uintptr_t DecreaseSpeed = 0x1387D60; // void
		constexpr uintptr_t Accelerate = 0x13879A0; // void
		constexpr uintptr_t Decelerate = 0x1387C90; // void
		constexpr uintptr_t NoClipUpdate = 0x1388040; // void
		constexpr uintptr_t SpeedUpdate = 0x1389540; // void
		constexpr uintptr_t AccererationUpdate = 0x1387A70; // void
		constexpr uintptr_t PositionUpdate = 0x1389450; // void
		constexpr uintptr_t get_SpeedStat = 0x1389760; // SpeedStat
		constexpr uintptr_t get_IsMoving = 0x10C9130; // bool
		constexpr uintptr_t set_IsMoving = 0x489A70; // void
		constexpr uintptr_t get_MinimalSpeed = 0x1389710; // bool
		constexpr uintptr_t get_CurrentSpeed = 0x13896D0; // ObscuredFloat
		constexpr uintptr_t set_CurrentSpeed = 0x13897D0; // void
		constexpr uintptr_t get_TargetSpeed = 0x13897B0; // ObscuredFloat
		constexpr uintptr_t set_TargetSpeed = 0x1389810; // void
		constexpr uintptr_t get_MaxSpeed = 0x13896F0; // ObscuredFloat
		constexpr uintptr_t set_MaxSpeed = 0x13897F0; // void
		constexpr uintptr_t .ctor = 0x1389640; // void
	}

	// Hyperstrange.WARPZ.PlayerWarpComponent
	namespace PlayerWarpComponent {
		// Fields
		constexpr uintptr_t _hitInfo = 0x48; // RaycastHit
		constexpr uintptr_t _currentHittable = 0x78; // IHittable
		constexpr uintptr_t <CurrentWarpableDuration>k__BackingField = 0x80; // float
		constexpr uintptr_t <CurrentPanel>k__BackingField = 0x88; // Panel

		// Methods
		constexpr uintptr_t OnEnable = 0x132E7C0; // void
		constexpr uintptr_t OnDisable = 0x132E6B0; // void
		constexpr uintptr_t OnWarpDown = 0x132EB30; // void
		constexpr uintptr_t HandleWarp = 0x132E510; // void
		constexpr uintptr_t get_LastHitInfo = 0x132EBE0; // RaycastHit
		constexpr uintptr_t get_WarpableFound = 0x132EC10; // bool
		constexpr uintptr_t get_CurrentWarpableDuration = 0x132EBD0; // float
		constexpr uintptr_t set_CurrentWarpableDuration = 0x132EC60; // void
		constexpr uintptr_t get_CurrentPanel = 0x3FA760; // Panel
		constexpr uintptr_t set_CurrentPanel = 0x6583E0; // void
		constexpr uintptr_t .ctor = 0x132EB90; // void
	}

	// Hyperstrange.WARPZ.PlayerComboComponent
	namespace PlayerComboComponent {
		// Fields
		constexpr uintptr_t _comboTimeout = 0x48; // float
		constexpr uintptr_t _activeCombo = 0x4C; // bool
		constexpr uintptr_t _lastComboIncrementTimeStamp = 0x50; // float
		constexpr uintptr_t <ComboTimeoutProgress>k__BackingField = 0x54; // float
		constexpr uintptr_t <ComboCount>k__BackingField = 0x58; // int

		// Methods
		constexpr uintptr_t OnEnable = 0x1382F70; // void
		constexpr uintptr_t OnDisable = 0x1382C60; // void
		constexpr uintptr_t OnRespawn = 0x1383280; // void
		constexpr uintptr_t OnWarpSuccess = 0x1383360; // void
		constexpr uintptr_t OnWarpFail = 0x1382BD0; // void
		constexpr uintptr_t OnBreak = 0x1382BD0; // void
		constexpr uintptr_t BreakCombo = 0x1382BD0; // void
		constexpr uintptr_t IncrementCombo = 0x1382BE0; // void
		constexpr uintptr_t get_ComboTimeout = 0xDB1780; // float
		constexpr uintptr_t get_ComboTimeoutProgress = 0x71D7F0; // float
		constexpr uintptr_t set_ComboTimeoutProgress = 0x71D8D0; // void
		constexpr uintptr_t get_ComboCount = 0x5B7B80; // int
		constexpr uintptr_t set_ComboCount = 0x5B8010; // void
		constexpr uintptr_t .ctor = 0x1383370; // void
	}
}
