#pragma once
// Auto-generated offsets from IL2CPP dump
// Generated by offset_finder.py
// DO NOT EDIT MANUALLY - Run `python tools/offset_finder.py` to regenerate

#include <cstdint>

namespace Offsets {
	// UnityEngine.Camera
	namespace Camera {
		// Methods
		constexpr uintptr_t WorldToScreenPoint = 0x7AAC40; // Vector3 (from your manual search)
		constexpr uintptr_t get_main = 0x7AB060; // Camera
	}

	// UnityEngine.Transform
	namespace Transform {
		// Methods
		constexpr uintptr_t get_position = 0x9FAE30; // Vector3 (from your manual search)
		constexpr uintptr_t set_position = 0x9FB550; // void
		constexpr uintptr_t get_rotation = 0x9FAFF0; // Quaternion
		constexpr uintptr_t set_rotation = 0x9FB640; // void
	}

	// Hyperstrange.WARPZ.Panel (base class)
	namespace Panel {
		// This is a base class that FinishPanel inherits from
		// We'll find instances at runtime using IL2CPP
	}

	// Hyperstrange.WARPZ.Player
	namespace Player {
		// Fields
		constexpr uintptr_t _cameraTransform = 0xD0; // Transform
		constexpr uintptr_t _playerSpawnPoint = 0xD8; // PlayerSpawnPoint
		constexpr uintptr_t _movementComponent = 0xE0; // PlayerMovementComponent
		constexpr uintptr_t _timeComponent = 0xE8; // PlayerTimeComponent
		constexpr uintptr_t _statsComponent = 0xF0; // PlayerStatsComponent
		constexpr uintptr_t _debugComponent = 0xF8; // PlayerDebugComponent
		constexpr uintptr_t Camera = 0x100; // Camera (removed angle brackets from name)
		constexpr uintptr_t IsActive = 0x108; // bool
		constexpr uintptr_t WarpComponent = 0x110; // PlayerWarpComponent
		constexpr uintptr_t ComboComponent = 0x118; // PlayerComboComponent

		// Methods
		constexpr uintptr_t Awake = 0x138C7C0; // void
		constexpr uintptr_t get_Camera = 0x2DA4F0; // Camera
		constexpr uintptr_t get_CameraTransform = 0x585F20; // Transform
		constexpr uintptr_t get_IsActive = 0x2DA510; // bool
		constexpr uintptr_t get_CurrentSpeed = 0x138E0C0; // ObscuredFloat
		constexpr uintptr_t get_DebugNoClip = 0x138E140; // bool
	}

	// Hyperstrange.WARPZ.TimeManager
	namespace TimeManager {
		// Methods
		constexpr uintptr_t SetTimeScale = 0x1345B80; // void
		constexpr uintptr_t get_CurrentTimeScale = 0x1345DC0; // float
		constexpr uintptr_t set_CurrentTimeScale = 0x1345E20; // void
	}

	// Hyperstrange.WARPZ.PlayerMovementComponent
	namespace PlayerMovementComponent {
		// Fields
		constexpr uintptr_t CurrentSpeed = 0x8C; // ObscuredFloat

		// Methods
		constexpr uintptr_t NoClipUpdate = 0x1388040; // void
	}
}
